version: "3.8"

services:
  mongo:
    image: mongo:6.0.4
    volumes:
      - ./db/mongo/data/db:/data/db
      - ./db/mongo/data/log:/data/log
      - ./db/mongo/data/dump:/data/dump
    ports:
      - "27017:27017"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"

  # 创建好MySQL后，需要在服务中执行StcokCrawler/mysql.sql脚本以创建数据库
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/log:/var/log/mysql
      - ./db/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  sk-service:
    depends_on:
      - mongo
      - mysql
    build: ./SemanticKernelService
    ports:
      - "5095:5095"

  crawler-service:
    depends_on:
      - mongo
      - mysql
    build: ./StockCrawler
    ports:
      - "8000:8000"

  web:
    depends_on:
      - mongo
      - mysql
      - sk-service
      - crawler-service
    build: ./StockForecastWeb
    ports:
      - "8080:8080"